spring.application.name=WebRestaurant

spring.datasource.url=jdbc:postgresql://localhost:5432/Restaurant
spring.datasource.username=postgres
spring.datasource.password=lhh92040442

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true